[package]
name = "cheesecake"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "cake"
path = "src/main.rs"

[profile.release]
opt-level = "s"
strip = true
lto = "thin"

[dependencies]
clap = "4.5.34"
