name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: rustup toolchain install stable --profile minimal --target wasm32-unknown-unknown --no-self-update

    - name: Run tests
      run: cargo test --verbose

    - name: Lint
      run: cargo clippy --verbose
