[package]
name = "view"
version = "0.1.0"
edition = "2024"

[lib]
path = "lib.rs"

[dependencies]
hotwatch = "0.5.0"
minify-html = "0.16.4"
serde = "1.0.219"
serde_json = "1.0.140"
tera = "1.20.0"
thiserror = "2.0.12"
